version: "3.7"

services:
    database:
        image: mysql:5.7
        container_name: seryum-database
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: seryum
            MYSQL_PASSWORD: Seryum_1
        networks:
            - seryumnet
    myapp:
        image: seryum65/bookstoreapp:latest
        container_name: myapp
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - seryumnet        
networks:
    seryumnet:
