# apiVersion: v1
# kind: Service   
# metadata:
#   name: web-flask-svc
#   labels:
#     app: web-flask
# spec:
#   type: ClusterIP  
#   ports:
#   - port: 3000  
#     targetPort: 5000
#   selector:
#     env: front-end 

# apiVersion: v1
# kind: Service   
# metadata:
#   name: web-flask-svc
#   labels:
#     app: web-flask
# spec:
#   type: NodePort  
#   ports:
#   - port: 3000  
#     targetPort: 5000
#   selector:
#     env: front-end 

# apiVersion: v1
# kind: Service   
# metadata:
#   name: web-flask-svc
#   labels:
#     app: web-flask
# spec:
#   type: NodePort 
#   ports:
#   - nodePort: 30036  
#     port: 3000        
#     targetPort: 5000
#   selector:
#     env: front-end

# apiVersion: v1
# kind: Service
# metadata:
#   name: web-flask-svc
#   labels:
#     app: web-flask
# spec:
#   type: NodePort
#   ports:
#   - port: 3000
#     nodePort: 30036
#     targetPort: 5000
#   selector:
#     env: front-end
#     version: v1


apiVersion: v1
kind: Service
metadata:
  name: web-flask-svc
  namespace: demo
  labels:
    app: web-flask
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 5000
    nodePort: 30036
  selector:
    env: front-end