apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: seryum65/phonebook-main
        name: phonebook-main
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_PASSWORD
            #value: Yusuf_1
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
        envFrom:
          - configMapRef:
              name: server-config
          # - name: MYSQL_USER
          #   value: seryum
          # - name: MYSQL_DATABASE
          #   value: phonebook
          # - name: MYSQL_DATABASE_HOST
          #   value: mysql-service
        resources: {}

