# plugin: aws_ec2
# regions:
#   - "us-east-1"
# keyed_groups:
#   - key: tags.Name
# compose:
#   ansible_host: public_ip_address
#   foo: private_ip_address


# plugin: aws_ec2
# regions:
#   - us-east-1
# keyed_groups:
#   - key: tags.Name
# compose:
#   ansible_host: public_ip_adress
# filters:
#   instance-state-name: running
#   tag:env: ansible

plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
  - prefix: arch
    key: architecture
  - prefix: tag
    key: tags
  - prefix: region
    key: placement.region
  - prefix: instance_type
    key: instance_type
compose:
  ansible_host: public_ip_adress
  foo: private_ip_address
  boo: instance_id
  key: key_name
filters:
  instance-state-name: running
