- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: lisa
    ansible_ssh_private_key_file: "/home/ec2-user/firstkey.pem"
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"


# - name: create a user using a variable
#   hosts: all
#   become: true
#   vars:
#     user: lisa
#   tasks:
#     - name: create a user {{ user }}
#       user:
#         name: "{{ user }}"
#     - debug:
#         msg: "private_ip is {{ foo }}"

#     - debug:
#         msg: "instance_id is {{ boo }}"

#     - debug:
#         msg: "my key pem is {{ key }}"

#     - debug:
#         msg: "host is {{ ansible_host }}"

#     -  debug:
#         msg: "user name is {{ user | upper }}"

#     - - debug:
#         msg: "{{ [1, 2, 3, 4] | min }}"